// This file is generated by `scripts/run_with_api_gateway.ps1` when you
// run the mobile app against a deployed stack. It provides a runtime
// fallback for the API Gateway URL so builds that include the generated
// file will use the deployed endpoint even if no --dart-define is passed.

// If empty, no generated API Gateway URL was written.
const String generatedApiGatewayUrl = "https://8vkj44idn5.execute-api.eu-north-1.amazonaws.com/Prod";
